# Generated by Django 4.1.2 on 2022-10-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
